server:
  shutdown: graceful
spring:
  datasource:
    url: jdbc:mysql://88.222.242.187:3306/schools_finance
    username: root
    password: Root@1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  sleuth:
    enabled: true
  zipkin:
    enabled: true
    baseUrl: http://zipkin-container:9411/
  flyway:
    baseline-on-migrate: true
  kafka:
    bootstrap-servers: 88.222.242.187:9092
eureka:
  client:
    enabled: true
    service-Url:
      defaultZone: http://eureka-container:8071/eureka/
    fetchRegistry: true
    registerWithEureka: true
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10  # Interval to renew the lease
    leaseExpirationDurationInSeconds: 30  # Timeout for removing an instance
services:
  information:
    url: http://information-container:8072/
jwt:
  secret: secret
management:
    endpoints:
      web:
        exposure:
          include: "*"
