spring:
  datasource:
    url: jdbc:mysql://88.222.242.187:3306/schools_finance
    username: root
    password: Root@1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  zipkin:
    base-url: http://88.222.242.187:9411/
  flyway:
    baseline-on-migrate: true
  kafka:
    bootstrap-servers: 88.222.242.187:9092
eureka:
  client:
    enabled: true
    service-Url:
      defaultZone: http://172.18.0.2:8071/eureka/
    fetchRegistry: true
    registerWithEureka: true
  instance:
    preferIpAddress: true
services:
  information:
    url: http://88.222.242.187:8072/
jwt:
  secret: secret
management:
    endpoints:
      web:
        exposure:
          include: "*"
