spring:
  datasource:
    url: jdbc:mysql://localhost:3306/schools_finance
    username: root
    password: root123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  zipkin:
    base-url: http://localhost:9411/
  flyway:
    baseline-on-migrate: true
  kafka:
    bootstrap-servers: localhost:9092
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8071/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
services:
  information:
    url: http://localhost:8072/
