spring:
  datasource:
    url: jdbc:mysql://82.112.230.73:3306/schools_finance
    username: new_admin
    password: new_password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  zipkin:
    base-url: http://82.112.230.73:9411/
  flyway:
    baseline-on-migrate: true
  kafka:
    bootstrap-servers: 82.112.230.73:9092
eureka:
  client:
    enabled: true
    service-Url:
      defaultZone: http://172.18.0.2:8071/eureka/
    fetchRegistry: true
    registerWithEureka: true
  instance:
    preferIpAddress: true
services:
  information:
    url: http://82.112.230.73:8072/
jwt:
  secret: secret
management:
    endpoints:
      web:
        exposure:
          include: "*"
