management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  sleuth:
    enabled: false
  zipkin:
    enabled: false
eureka:
  client:
    enabled: true
    service-Url:
      defaultZone: http://localhost:8071/eureka/
    fetchRegistry: true
    registerWithEureka: true
  instance:
    preferIpAddress: true
jwt:
  secret: secret
logging:
  level:
    com:
      theschools:
        gateway: DEBUG