server:
  shutdown: graceful
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  sleuth:
    enabled: true
  zipkin:
    enabled: true
    baseUrl: http://zipkin-container:9411/

eureka:
  client:
    enabled: true
    service-Url:
      defaultZone: http://eureka-container:8071/eureka/
    fetchRegistry: true
    registerWithEureka: true
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10  # Interval to renew the lease
    leaseExpirationDurationInSeconds: 30  # Timeout for removing an instance
jwt:
  secret: secret
logging:
  level:
    com:
      theschools:
        gateway: DEBUG