spring:
  datasource:
    url: jdbc:mysql://localhost:3306/schools_info
    username: root
    password: root123
  zipkin:
    base-url: http://localhost:9411/
  flyway:
    baseline-on-migrate: true
  kafka:
    bootstrap-servers: localhost:9092
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
services:
  security:
    url: http://localhost:8075/
  finance:
    url: http://localhost:8074/

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8071/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    preferIpaddress: true
