# For Prod Profile
spring:
  datasource:
    url: jdbc:mysql://88.222.242.187:3306/schools_security
    username: root
    password: Root@1234
  zipkin:
    base-url: http://88.222.242.187:9411/
  flyway:
    baseline-on-migrate: true
  security:
    user:
      name: admin
      password: admin
  oauth2:
    client:
      registration:
        google:
          client-id: <your-google-client-id>
          client-secret: <your-google-client-secret>
        facebook:
          client-id: <your-facebook-client-id>
          client-secret: <your-facebook-client-secret>
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
eureka:
  client:
    enabled: true
    service-Url:
      defaultZone: http://172.18.0.2:8071/eureka/
    fetchRegistry: true
    registerWithEureka: true
  instance:
    preferIpAddress: true
logging:
  level:
    org:
      springframework:
        security: DEBUG
services:
  information:
    url: http://88.222.242.187:8072/
management:
    endpoints:
      web:
        exposure:
          include: "*"



