# For local Profile
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/schools_security
    username: root
    password: root123
  zipkin:
    base-url: http://localhost:9411/
  flyway:
    baseline-on-migrate: true
  security:
    user:
      name: admin
      password: admin
  oauth2:
    client:
      registration:
        google:
          client-id: <your-google-client-id>
          client-secret: <your-google-client-secret>
        facebook:
          client-id: <your-facebook-client-id>
          client-secret: <your-facebook-client-secret>
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8071/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    preferIpaddress: true
logging:
  level:
    org:
      springframework:
        security: DEBUG
services:
  information:
    url: http://localhost:8072/



